linters:
  # https://golangci-lint.run/usage/linters/
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - makezero
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sloglint
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  godot:
    exclude:
      - "^ @"

  varnamelen:
    ignore-names:
      - err
      - id
      - k
      - i
      - v

issues:
  exclude-rules:
      - path: _test\.go
        linters:
          - funlen
          - lll