// Code generated by MockGen. DO NOT EDIT.
// Source: client_interface.go
//
// Generated by this command:
//
//	mockgen -source=client_interface.go -destination client_mock_gen.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	http "net/http"
	reflect "reflect"

	traderepublic "github.com/dhojayev/traderepublic-portfolio-downloader/v2/pkg/traderepublic"
	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockClientInterface) Login(requestBody traderepublic.APILoginRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", requestBody)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockClientInterfaceMockRecorder) Login(requestBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClientInterface)(nil).Login), requestBody)
}

// PostOTP mocks base method.
func (m *MockClientInterface) PostOTP(processID, otp string) ([]*http.Cookie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostOTP", processID, otp)
	ret0, _ := ret[0].([]*http.Cookie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostOTP indicates an expected call of PostOTP.
func (mr *MockClientInterfaceMockRecorder) PostOTP(processID, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostOTP", reflect.TypeOf((*MockClientInterface)(nil).PostOTP), processID, otp)
}
