// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package instrument

import (
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/database"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func ProvideModelBuilder(logger *logrus.Logger) ModelBuilder {
	typeResolver := NewTypeResolver(logger)
	modelBuilder := NewModelBuilder(typeResolver, logger)
	return modelBuilder
}

// wire.go:

func ProvideInstrumentRepository(db *gorm.DB, logger *logrus.Logger) (*database.Repository[*Model], error) {
	return database.NewRepository[*Model](db, logger)
}
