// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package activity

import (
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/api/timeline/activitylog"
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/api/timeline/details"
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/portfolio/document"
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/reader"
	"github.com/dhojayev/traderepublic-portfolio-downloader/internal/writer"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func ProvideHandler(responseReader reader.Interface, responseWriter writer.Interface, logger *logrus.Logger) (Handler, error) {
	client := activitylog.NewClient(responseReader, logger)
	detailsClient := details.NewClient(responseReader, logger)
	activityLogResponseNormalizer := details.NewActivityResponseNormalizer(logger)
	dateResolver := document.NewDateResolver(logger)
	modelBuilder := document.NewModelBuilder(dateResolver, logger)
	downloader := document.NewDownloader(logger)
	processor := NewProcessor(modelBuilder, downloader, logger)
	handler := NewHandler(client, detailsClient, activityLogResponseNormalizer, processor, logger)
	return handler, nil
}
