# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json

package: traderepublic
generate:
  models: true
  client: true
  strict-server: false
  chi-server: false
  embedded-spec: true
  server-urls: true
