// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination client_mock.go -package=auth
//

// Package auth is a generated GoMock package.
package auth
