// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination client_mock.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	reflect "reflect"

	api "github.com/dhojayev/traderepublic-portfolio-downloader/internal/api"
	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockClientInterface) Login(phoneNumber, pin string) (api.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", phoneNumber, pin)
	ret0, _ := ret[0].(api.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockClientInterfaceMockRecorder) Login(phoneNumber, pin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClientInterface)(nil).Login), phoneNumber, pin)
}

// ProvideOTP mocks base method.
func (m *MockClientInterface) ProvideOTP(processID, otp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvideOTP", processID, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProvideOTP indicates an expected call of ProvideOTP.
func (mr *MockClientInterfaceMockRecorder) ProvideOTP(processID, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideOTP", reflect.TypeOf((*MockClientInterface)(nil).ProvideOTP), processID, otp)
}

// SessionToken mocks base method.
func (m *MockClientInterface) SessionToken() api.Token {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionToken")
	ret0, _ := ret[0].(api.Token)
	return ret0
}

// SessionToken indicates an expected call of SessionToken.
func (mr *MockClientInterfaceMockRecorder) SessionToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionToken", reflect.TypeOf((*MockClientInterface)(nil).SessionToken))
}
